language: node_js

script:
  - npm test -g .imptest-auth

before_install:
  - openssl aes-256-cbc -K $encrypted_1c10239a1837_key -iv $encrypted_1c10239a1837_iv -in .imptest-auth.enc -out .imptest-auth -d
